# Default Maintenance Locations created on install (and for existing sites by a patch).
# "General" locations are shown for every facility type set in Maintenance Settings.

DEFAULT_LOCATIONS = [
	{
		"location_name": "Guest Room",
		"facility_type": "Hotel",
		"requires_room_number": 1,
		"issues": [
			"Bed (king, queen, twin, etc.)",
			"Nightstand",
			"Dresser/Closet",
			"Desk/Workspace",
			"Television",
			"Safe",
			"Mini fridge/Minibar",
			"Coffee maker/kettle",
			"Iron and ironing board",
			"Alarm clock",
			"Seating area (armchair, sofa)",
			"Phone",
			"Air conditioning/heating control",
			"Full-length mirror",
			"Ensuite bathroom",
		],
	},
	{
		"location_name": "Lobby",
		"facility_type": "Hotel",
		"requires_room_number": 0,
		"issues": [
			"Reception desk",
			"Seating area",
			"Information kiosk or concierge",
			"Luggage storage",
			"Digital information displays",
			"Magazine rack/newspaper stand",
			"Water station",
			"ATM",
			"Public restrooms",
			"Business center corner (computers, printer)",
		],
	},
	{
		"location_name": "Lounge Area",
		"facility_type": "Hotel",
		"requires_room_number": 0,
		"issues": [
			"Comfortable seating (sofas, armchairs)",
			"Coffee tables",
			"Charging stations",
			"Magazines and newspapers",
			"Beverage service area",
			"Television(s)",
			"Art or decor installations",
			"Ambient lighting",
			"Speaker system",
		],
	},
	{
		"location_name": "Pool Area",
		"facility_type": "Hotel",
		"requires_room_number": 0,
		"issues": [
			"Pool chairs/loungers",
			"Towels",
			"Umbrellas/shaded areas",
			"Poolside bar",
			"Lifeguard station (if applicable)",
			"Changing rooms and showers",
			"Hot tub/jacuzzi",
			"Pool toys or floaties",
			"Water fountain/drink station",
			"Rinsing station",
		],
	},
	{
		"location_name": "Gym/Fitness Center",
		"facility_type": "Hotel",
		"requires_room_number": 0,
		"issues": [
			"Treadmills and cardio machines",
			"Weightlifting equipment (dumbbells, barbells)",
			"Yoga mats/stretching area",
			"Resistance bands",
			"Towels and water station",
			"Television(s)",
			"Mirrors",
			"Locker room",
			"Showers",
			"Sauna or steam room (sometimes)",
		],
	},
	{
		"location_name": "Spa",
		"facility_type": "Hotel",
		"requires_room_number": 0,
		"issues": [
			"Treatment rooms (massage, facials)",
			"Relaxation lounge",
			"Aromatherapy station",
			"Sauna and steam rooms",
			"Jacuzzi/hot tub",
			"Showers",
			"Changing rooms/lockers",
			"Robes and slippers",
			"Tea/water station",
			"Reception and retail area (for spa products)",
		],
	},
	{
		"location_name": "Hotel Bar",
		"facility_type": "Hotel",
		"requires_room_number": 0,
		"issues": [
			"Bar counter and seating",
			"High tables/stools",
			"Lounge seating",
			"Dance floor (if applicable)",
			"Live entertainment stage (if applicable)",
			"Menu displays",
			"Televisions",
			"Bar games (pool table, darts)",
			"Music system",
			"Beverage and snack menu",
		],
	},
	{
		"location_name": "Restaurant",
		"facility_type": "Hotel",
		"requires_room_number": 0,
		"issues": [
			"Dining tables and chairs",
			"Host/Reception stand",
			"Menu stands/displays",
			"Bar or beverage counter",
			"Buffet stations (if applicable)",
			"Private dining area (in some cases)",
			"Tableware (utensils, glasses)",
			"High chairs/booster seats",
			"Kitchen (back-of-house)",
			"Restrooms nearby",
		],
	},
	{
		"location_name": "Conference Hall",
		"facility_type": "Hotel",
		"requires_room_number": 0,
		"issues": [
			"Stage or podium",
			"Projector and screen",
			"Audio-visual equipment (microphones, speakers)",
			"Seating (movable or fixed)",
			"Lighting controls",
			"Presentation boards/whiteboards",
			"Charging stations",
			"Refreshment area (coffee, water)",
			"Restrooms nearby",
			"Registration desk (if needed)",
		],
	},
	{
		"location_name": "Meeting Room",
		"facility_type": "General",
		"requires_room_number": 0,
		"issues": [
			"Conference table",
			"Chairs",
			"Whiteboard or flip chart",
			"Projector or screen",
			"Telephone for conference calls",
			"Notepads and pens",
			"Refreshment station",
			"Video conferencing equipment",
			"Charging outlets",
			"Lighting controls",
		],
	},
	{
		"location_name": "Banquet Hall",
		"facility_type": "Hotel",
		"requires_room_number": 0,
		"issues": [
			"Movable tables and chairs",
			"Stage or podium",
			"Dance floor",
			"Audio-visual equipment (speakers, mics)",
			"Buffet or catering area",
			"Decor options (lighting, drapes)",
			"Restrooms nearby",
			"Coat check area",
			"Bar setup (sometimes)",
		],
	},
	{
		"location_name": "Rooftop Bar",
		"facility_type": "Hotel",
		"requires_room_number": 0,
		"issues": [
			"Seating (high tables, loungers)",
			"Bar counter",
			"Fire pits/heaters",
			"Lighting fixtures",
			"Umbrellas or awnings",
			"DJ booth (if applicable)",
			"Plants or greenery",
			"View points or telescopes",
			"Small dining area",
			"Ambient music",
		],
	},
	{
		"location_name": "Business Center",
		"facility_type": "Hotel",
		"requires_room_number": 0,
		"issues": [
			"Computers",
			"Printers and scanners",
			"Fax machine",
			"Copy machine",
			"Workstations or desks",
			"Office supplies (stapler, paper, etc.)",
			"Charging stations",
			"Conference room booking service",
			"Telephones",
			"Secure internet access",
		],
	},
	{
		"location_name": "Elevators",
		"facility_type": "General",
		"requires_room_number": 0,
		"issues": [
			"Directory of floors",
			"Mirror or reflective panels",
			"Handrail",
			"Security camera",
			"Emergency buttons",
			"Soft lighting",
			"Braille panels for accessibility",
		],
	},
	{
		"location_name": "Parking Lot",
		"facility_type": "General",
		"requires_room_number": 0,
		"issues": [
			"Parking spaces",
			"EV charging stations",
			"Lighting poles",
			"Security cameras",
			"Signage for directions",
			"Handicap parking spots",
			"Payment kiosk (if applicable)",
			"Bicycle racks",
			"Loading zones",
		],
	},
	{
		"location_name": "Reception Desk",
		"facility_type": "General",
		"requires_room_number": 0,
		"issues": [
			"Concierge service",
			"Key card printing",
			"Luggage storage area",
			"Information brochures",
			"Charging stations",
			"Guest book or sign-in screen",
			"Digital signage",
			"ATM or currency exchange (sometimes)",
		],
	},
	{
		"location_name": "Garden/Patio",
		"facility_type": "Hotel",
		"requires_room_number": 0,
		"issues": [
			"Seating (benches, tables)",
			"Pathways and walkways",
			"Water features (fountains, ponds)",
			"Plants and landscaping",
			"Gazebo or shaded area",
			"Outdoor lighting",
			"BBQ grills (in some patios)",
			"Playground (family-friendly hotels)",
			"Decorative sculptures",
		],
	},
	{
		"location_name": "Terrace",
		"facility_type": "Hotel",
		"requires_room_number": 0,
		"issues": [
			"Seating (tables, loungers)",
			"Fire pits or heaters",
			"Umbrellas/shades",
			"Plants and greenery",
			"View points",
			"Lighting for evening ambiance",
			"Small bar or refreshment area",
			"Charging stations",
		],
	},
	{
		"location_name": "Ballroom",
		"facility_type": "Hotel",
		"requires_room_number": 0,
		"issues": [
			"Stage or podium",
			"Dance floor",
			"Movable tables and chairs",
			"Lighting controls (chandeliers, spotlights)",
			"Audio-visual equipment (projectors, microphones)",
			"Buffet/catering area",
			"Coat check",
			"Restrooms nearby",
			"Decor setup options (drapes, lights)",
		],
	},
	{
		"location_name": "Valet Parking Area",
		"facility_type": "Hotel",
		"requires_room_number": 0,
		"issues": [
			"Waiting area with seating",
			"Valet stand/booth",
			"Key storage rack",
			"Signage with valet rates",
			"Parking cones or markers",
			"Umbrella stand (for rainy weather)",
			"Security cameras",
			"Mobile payment system",
		],
	},
	{
		"location_name": "Other",
		"facility_type": "General",
		"requires_room_number": 0,
		"issues": ["General Inquiry", "Other"],
	},
	{
		"location_name": "Restrooms",
		"facility_type": "General",
		"requires_room_number": 0,
		"issues": [
			"Toilets",
			"Sinks and taps",
			"Hand dryers/paper towel dispensers",
			"Plumbing leaks",
			"Ventilation/extractor fan",
			"Lighting",
			"Doors and locks",
		],
	},
	{
		"location_name": "Classroom",
		"facility_type": "School",
		"requires_room_number": 1,
		"issues": [
			"Desks and chairs",
			"Whiteboard/chalkboard",
			"Projector or smart board",
			"Lighting",
			"Ceiling fan/air conditioning",
			"Windows",
			"Doors and locks",
			"Power sockets",
		],
	},
	{
		"location_name": "Science Laboratory",
		"facility_type": "School",
		"requires_room_number": 1,
		"issues": [
			"Lab benches",
			"Sinks and taps",
			"Gas taps/burners",
			"Fume cupboard",
			"Safety shower/eye wash",
			"Lab equipment",
			"Lighting",
			"Ventilation",
		],
	},
	{
		"location_name": "Computer Lab",
		"facility_type": "School",
		"requires_room_number": 1,
		"issues": [
			"Computers",
			"Network/internet",
			"Printers",
			"Projector",
			"Power sockets",
			"Air conditioning",
			"Chairs and desks",
		],
	},
	{
		"location_name": "Library",
		"facility_type": "School",
		"requires_room_number": 0,
		"issues": [
			"Bookshelves",
			"Reading tables and chairs",
			"Computers/catalogue terminals",
			"Lighting",
			"Air conditioning",
			"Photocopier",
		],
	},
	{
		"location_name": "Staff Room",
		"facility_type": "School",
		"requires_room_number": 0,
		"issues": [
			"Tables and chairs",
			"Kettle/microwave",
			"Refrigerator",
			"Lockers",
			"Air conditioning",
			"Lighting",
		],
	},
	{
		"location_name": "Administration Office",
		"facility_type": "School",
		"requires_room_number": 0,
		"issues": [
			"Desks and chairs",
			"Computers",
			"Printers and scanners",
			"Telephones",
			"Air conditioning",
			"Filing cabinets",
		],
	},
	{
		"location_name": "Dormitory/Hostel",
		"facility_type": "School",
		"requires_room_number": 1,
		"issues": [
			"Beds and mattresses",
			"Wardrobes/lockers",
			"Bathroom/showers",
			"Lighting",
			"Ceiling fan/air conditioning",
			"Windows",
			"Doors and locks",
			"Power sockets",
		],
	},
	{
		"location_name": "Dining Hall/Cafeteria",
		"facility_type": "School",
		"requires_room_number": 0,
		"issues": [
			"Tables and benches",
			"Serving counter",
			"Hand washing station",
			"Lighting",
			"Ceiling fans",
			"Drinking water dispenser",
		],
	},
	{
		"location_name": "School Kitchen",
		"facility_type": "School",
		"requires_room_number": 0,
		"issues": [
			"Cooking stoves/ovens",
			"Refrigerators/freezers",
			"Sinks and taps",
			"Extractor hood",
			"Gas supply",
			"Food storage shelves",
		],
	},
	{
		"location_name": "Assembly Hall",
		"facility_type": "School",
		"requires_room_number": 0,
		"issues": [
			"Stage",
			"Seating",
			"Sound system/microphones",
			"Projector and screen",
			"Lighting",
			"Ceiling fans",
		],
	},
	{
		"location_name": "Sports Field",
		"facility_type": "School",
		"requires_room_number": 0,
		"issues": [
			"Goal posts",
			"Field markings",
			"Fencing",
			"Floodlights",
			"Spectator stands",
			"Irrigation/sprinklers",
		],
	},
	{
		"location_name": "Gymnasium/Sports Hall",
		"facility_type": "School",
		"requires_room_number": 0,
		"issues": [
			"Flooring",
			"Basketball hoops",
			"Sports equipment",
			"Changing rooms",
			"Showers",
			"Lighting",
		],
	},
	{
		"location_name": "Sick Bay/Clinic",
		"facility_type": "School",
		"requires_room_number": 0,
		"issues": [
			"Beds",
			"First aid supplies cabinet",
			"Sink",
			"Refrigerator",
			"Lighting",
			"Air conditioning",
		],
	},
	{
		"location_name": "Playground",
		"facility_type": "School",
		"requires_room_number": 0,
		"issues": ["Swings", "Slides", "Climbing frames", "Benches", "Fencing", "Surface/flooring"],
	},
	{
		"location_name": "Open Workspace",
		"facility_type": "Office",
		"requires_room_number": 0,
		"issues": [
			"Desks and chairs",
			"Power sockets",
			"Network/internet",
			"Lighting",
			"Air conditioning",
			"Partitions",
		],
	},
	{
		"location_name": "Private Office",
		"facility_type": "Office",
		"requires_room_number": 1,
		"issues": [
			"Desk and chair",
			"Computer",
			"Power sockets",
			"Air conditioning",
			"Lighting",
			"Door lock",
			"Window blinds",
		],
	},
	{
		"location_name": "Boardroom",
		"facility_type": "Office",
		"requires_room_number": 0,
		"issues": [
			"Conference table",
			"Chairs",
			"Display screen/projector",
			"Video conferencing equipment",
			"Speakerphone",
			"Air conditioning",
			"Lighting",
		],
	},
	{
		"location_name": "Break Room/Pantry",
		"facility_type": "Office",
		"requires_room_number": 0,
		"issues": [
			"Coffee machine/kettle",
			"Microwave",
			"Refrigerator",
			"Water dispenser",
			"Sink",
			"Tables and chairs",
		],
	},
	{
		"location_name": "Server Room",
		"facility_type": "Office",
		"requires_room_number": 0,
		"issues": [
			"Server racks",
			"Air conditioning/cooling",
			"UPS/power backup",
			"Network switches",
			"Fire suppression",
			"Access control",
		],
	},
	{
		"location_name": "Print/Copy Room",
		"facility_type": "Office",
		"requires_room_number": 0,
		"issues": ["Printers", "Photocopier", "Scanner", "Paper supplies", "Power sockets"],
	},
	{
		"location_name": "Storage Room",
		"facility_type": "Office",
		"requires_room_number": 0,
		"issues": ["Shelving", "Lighting", "Door lock", "Ventilation"],
	},
	{
		"location_name": "Office Lobby",
		"facility_type": "Office",
		"requires_room_number": 0,
		"issues": [
			"Reception seating",
			"Access control/turnstiles",
			"Visitor sign-in screen",
			"Lighting",
			"Main doors",
		],
	},
]
